name: 錯誤報告（繁體中文）
description: 提交 強化村民 錯誤報告
title: "[Bug] "
labels: ["Bug", "In triage"]
body:
  - type: markdown
    attributes:
      value: |
        感謝您抽出寶貴時間填寫此錯誤報告！
  - type: textarea
    id: what-happened
    attributes:
      label: 錯誤描述
      description: 請詳細描述發生的錯誤資訊。
      placeholder: 告訴我們發生了什麼錯誤。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 重現步驟
      description: 請描述觸發錯誤的步驟。
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: 預期行為
      description: 請簡要描述您想要的效果。
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: 實際行為
      description: 請簡要說明實際結果。
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 強化村民 版本
      description: 你目前使用的是什麼版本的 強化村民？（例如 1.1.3，從附加包標題中指示的版本號中找到）
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: 您正在使用的裝置的系統是什麼？
      options:
        - Windows
        - iOS
        - Android
        - 其他
    validations:
      required: true