name: Bug Report (English)
description: Submit Strengthened Villager bug report
title: "[Bug] "
labels: ["Bug", "In triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Description of the Bug
      description: Please describe in detail the bug information that occurred.
      placeholder: Tell us what bug occurred.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please describe the step that triggered the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please give a brief description of the desired effect.
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please give a brief description of the actual result.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Strengthened Villager Version
      description: What version of Strengthened Villager are you currently using? (e.g. 1.1.6, found from the version number indicated in the title of the add-on. If the version you are using is not listed here, the version you are using is out of date. Please update to the latest version and try to reproduce the bug again.)
      options:
        - 1.1.6
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: What is the game version you are playing?
      description: (If the version you are using is not listed here, the version you are using is not supported. Please use the supported version and try to reproduce the bug again.)
      options:
        - 1.19.50
        - 1.19.41
        - 1.19.40
        - 1.19.31
        - 1.19.30
        - 1.19.20
        - 1.19.10
        - 1.19.2
        - 1.19.0
        - 1.18.30
        - 1.18.20
        - 1.18.12
        - 1.18.11
        - 1.18.10
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What is the system of the device you are using?
      options:
        - Windows
        - iOS
        - Android
        - Other
    validations:
      required: false